Support `linux-aarch64` (#80)
* ✨ `conda-forge.yml`: Add ARM64 support for Linux

Add `linux-aarch64` to the build matrix via `build_platform` cross-compilation from
`linux_64`.

* 📦 `meta.yaml`: put upper bound `<5.5` on Lua version

Running the build with Lua 5.5.0 resulted in an undefined reference to `luaL_openlibs`
error. There is most likely a compatibility issue with flook and the latest Lua
release (v5.5.0, Dec 2025), so we place an upper bound on the Lua requirements.

* MNT: Re-rendered with conda-smithy 3.58.0 and conda-forge-pinning 2026.03.25.06.06.53

Other tools:
- conda-build 25.9.0
- rattler-build 0.48.1
- rattler-build-conda-compat 1.4.9