📦 `meta.yaml`: put upper bound `<5.5` on Lua version
Running the build with Lua 5.5.0 resulted in an undefined reference to `luaL_openlibs`
error. There is most likely a compatibility issue with flook and the latest Lua
release (v5.5.0, Dec 2025), so we place an upper bound on the Lua requirements.